### ISSUE TITLE
Error spam (list index out of range, could not query sidecar)

### ISSUE THREAD

**Issue by nienkevanunen** [Snakemake-Profiles/slurm#113]
For a while now I've had the issue shown in the screenshots. My jobs seem to run fine, but I am being spammed with these errors at the same time. Also, before my jobs run the time is shown as "INVALID". I've tried reinstalling my whole conda environment but that doesn't seem to fix it, and I don't understand a whole lot about the slurm integration with Snakemake that I installed from here using cookiecutter. I used it for at least 10 months or so without issue, and I haven't changed anything. It could be related to something the IT changed on the cluster, but going to them for help about this I know from experience is going to end up nowhere. So hopefully someone could point me in the right direction, or maybe knows what the IT might've changed so I could perhaps e-mail them something more concrete. 

I've tried Snakemake 7.24.0 and 7.24.2.

![image](https://github.com/Snakemake-Profiles/slurm/assets/8579642/3d650a3a-02e1-46f8-9014-9c754bdd247d)

![image](https://github.com/Snakemake-Profiles/slurm/assets/8579642/b682829e-3765-45f2-9b6c-bbf734105888)
(ignore the PartitionTimeLimit ones, they've just stuck in limbo there for a long time ...)

**Comment by mbhall88** [comment]
Might be related to #96

**Comment by mbhall88** [comment]
@nienkevanunen I just started having the same issue and I can confirm the patch fix in #96 worked for me

**Comment by nienkevanunen** [comment]
I applied the patch, and also getting the ```Could not parse ' '(try x of 10)```, like someone else in the comments of the issue, but I suppose its better than the previous spam. 😅

![image](https://github.com/Snakemake-Profiles/slurm/assets/8579642/29791330-680a-4392-87fb-81d96065b3e4)

**Comment by percyfal** [comment]
Hopefully fixed via #115. Feel free to reopen should the issue reemerge.
