### ISSUE TITLE
Error in slurm-submit-advanced.py

### ISSUE THREAD

**Issue by brand-fabian** [Snakemake-Profiles/slurm#17]
Hi,

when using `slurm-submit-advanced.py`as submission script against a slurm-18.08 cluster the function `_get_cluster_configuration` throws an error if the max. walltime of jobs for the given partition is less than a day. 

On our cluster, `sinfo -e -O "partition,..,time,..." -h -p <partition>` returns something akin to

    short          ...            5:00:00               ...

which violates the regex used for parsing the sinfo output in `_get_cluster_configuration`.

**Comment by percyfal** [comment]
Fixed via #21
