### ISSUE TITLE
How to use SLURM profile in combination with cluster.json

### ISSUE THREAD

**Issue by claczny** [Snakemake-Profiles/slurm#23]
Dear all,

I have set up a snakemake-based pipeline which makes use of snakemake's cluster submission functionalities on our HPC which uses SLURM.
While this works fine, snakemake does not terminate if a job was killed, e.g., because it ran out of reserved walltime. Johannes Köster suggested in https://bitbucket.org/snakemake/snakemake/issues/1259/snakemake-seems-not-to-terminate-when that the SLURM profile could (maybe) solve this.

As I have never used this snakemake functionality, I was wondering whether I would have to perform any special modifications (to the profile or my existing code)?

Concretely, I am running snakemake from the access node using a script including the following:

```
MAILUSER="my@email.com"

SLURM_ARGS="-p {cluster.partition} -N 1 -n {cluster.n} -c {cluster.ncpus} -t {cluster.time} --job-name={cluster.job-name} --mail-user ${MAILUSER} --mail-type {cluster.mail-type} -o {cluster.output} -e {cluster.error} {cluster.explicit}"
(date; conda activate my_env; snakemake -j 4 --cluster-config cluster.json --cluster "sbatch $SLURM_ARGS" -s Snakefile -p --use-conda ${TARGET} ; date) &> ${LOG}
```

and my `cluster.json` looks akin to the following:
```
{
    "__default__" :
    {
        "time" : "5-00:00:00",
        "n" : 1,
        "partition" : "batch",
        "ncpus": 1,
        "job-name" : "PROJECTNAME.{rule}",
        "output" : "slurm-%j.%N-%x.out",
        "error" : "slurm-%j.%N-%x.err",
        "explicit" : "",
        "mail-type"      : "NONE",
    },
    "unpack" :
    {
        "time" : "01-00:00:00",
        "n" : 1,
        "ncpus": 4
        "partition" : "batch",
    },
    "another_rule":
    {
        "time" : "05-00:00:00",
        "n" : 1,
        "ncpus": 28,
        "partition" : "other_batch",
        "mail-type" : "ALL",
    },
}
```

Put differently, for *specific* rules, I have defined *specific* resources (partitions, etc.) and *specific* behavior (should it send an email or not).

Could I just clone this repository and change my call to 
```
SLURM_ARGS="-p {cluster.partition} -N 1 -n {cluster.n} -c {cluster.ncpus} -t {cluster.time} --job-name={cluster.job-name} --mail-user ${MAILUSER} --mail-type {cluster.mail-type} -o {cluster.output} -e {cluster.error} {cluster.explicit}"
(date; conda activate my_env; snakemake -j 4 --cluster-config cluster.json --profile slurm --cluster "sbatch $SLURM_ARGS" -s Snakefile -p --use-conda ${TARGET} ; date) &> ${LOG}
```
i.e., simply adding `-- profile slurm`? Or did I  not really get the idea of the profile and I would have to perform more adjustments to my existing code?

Thank you very much and looking forward to your input!

Best,

Cedric

**Comment by percyfal** [comment]
Hi,

the advanced slurm submission script is designed to interact with cluster configuration files. Then, you should be able to run your submission above as 

`snakemake -j 4 --profile slurm --cluster-config cluster.json `

i.e. you don't have to pass the `--cluster` option. I haven't tested the mail settings though, and you may have to deal with the `explicit` flag separately as it is not in the default list of options in `slurm-submit-advanced.py`. You can always modify the latter for specific tweaks.

**Comment by percyfal** [comment]
Hi Cedric, closing this issue now  but feel free to reopen in case your needs haven't been addressed.
