### ISSUE TITLE
Is it possible to provide the --qos parameter via the slurm profile?

### ISSUE THREAD

**Issue by DidrikOlofsson** [Snakemake-Profiles/slurm#24]
Hi all!

First time I'm posting an issue here so sorry in advance if I'm a bit fuzzy. I'm trying to run snakemake using the slurm profile on our HPC where it is required to provide the `--qos` parameter when using `sbatch`. I couldn't find out if this is possible to input somehow and ended up adding `#SBATCH --qos=medium` as a new line in slurm-jobscript.sh which worked preliminarily. Is it possible to provide this parameter in a better way?

Best,
Didrik

**Comment by percyfal** [comment]
Hi,

I just added the `--qos` option to the submission scripts, will merge later today. Then you could use the advanced submission script together with a cluster configuration file  where you add a section for this option, e.g.:

`
__default__:
  qos: medium
`
and submit with snakemake --profile yourprofile --cluster-config cluster-config.yaml.

**Comment by DidrikOlofsson** [comment]
Hi,

tested the new version and still getting the following error message:

`sbatch: error: Please specify a QOS, e.g. '#SBATCH --qos=medium' (see 'sqos' for valid settings)`

Ran the snakemake command with `--profile slurm` and `--cluster-config cluster-config.yaml` as suggested with `__default__: qos: medium` in the cluster config.

**Comment by percyfal** [comment]
Hi, 

this issue should be fixed with PR #33. Could you verify?

**Comment by mwort** [comment]
This can probably be closed. See [here](https://github.com/Snakemake-Profiles/slurm#parsing-arguments-to-slurm-sbatch) to pass any parameter to sbatch.
