### ISSUE TITLE
Unit of time in cluster configs

### ISSUE THREAD

**Issue by ManavalanG** [Snakemake-Profiles/slurm#27]
When using `time` in cluster config, it looks like minutes is the only allowed unit with script `slurm-submit-advanced.py`. Is this correct? Is it possible to use hours, seconds, or days as units without converting them to minutes? 
https://github.com/Snakemake-Profiles/slurm/blob/4a67e7fdf7535fe80d588d7c96b08aedd791426d/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-submit-advanced.py#L245

Relevant description for `--time` from [slurm doc](https://slurm.schedmd.com/sbatch.html):
`Acceptable time formats include "minutes", "minutes:seconds", "hours:minutes:seconds", "days-hours", "days-hours:minutes" and "days-hours:minutes:seconds".`

**Comment by percyfal** [comment]
Hi, the limitation on using minutes has more to do with the fact that you can specify runtime in the resources section, which have to be integer valued:

https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources

One solution could be to write and apply a function `time_to_minutes` on your string representation of time in resources:

rule your_rule:
    resources: runtime = time_to_minutes("3-00:00:00")

**Comment by ManavalanG** [comment]
Thanks for the response! My scenario has more to do with using time in hour/day units when used with `--cluster -config` file. If I use time in the format suggested by slurm, `slurm-submit-advanced.py` exits with error as it is not an integer. I could change them to minutes, but it would loose readability.

Hope you don't mind me asking a question here unrelated to this :). When using snakemake profile and cluster config file (for eg., `snakemake --profile slurm --cluster-config cluster.json`), is it possible to override or add sbatch options? That is, something like:

```sh
snakemake --profile slurm --cluster-config cluster.json --cluster "--flag-not-in-cluster-config"
```

**Comment by percyfal** [comment]
Not that I know of - all calls, and options, to sbatch are handled by the submission script in your profile.

**Comment by ManavalanG** [comment]
Thanks!
