### ISSUE TITLE
Error submitting jobscript (exit code 1)

### ISSUE THREAD

**Issue by lczech** [Snakemake-Profiles/slurm#48]
Hi there,

I am getting the following error:

    Traceback (most recent call last):
      File "/path/to/pipeline/slurm-submit.py", line 52, in <module>
        sbatch_options = slurm_utils.format_values(sbatch_options, job_properties)
      File "/path/to/pipeline/slurm_utils.py", line 95, in format_values
        formatted[key] = format_wildcards(value, job_properties)
      File "/path/to/pipeline/slurm_utils.py", line 68, in format_wildcards
        job._format_params = Wildcards(fromdict=job_properties['params'])
    KeyError: 'params'
    Error submitting jobscript (exit code 1)

when submitting a job. As far as I can trace it back, the `job_properties` are set from the `slum-jobscript.sh` file, which does not contain `params` anywhere. But I might have traced that back wrongly, so not entirely sure where this error is coming from. 

Any help appreciated.

**Comment by johnstonmj** [comment]
My understanding is that slurm-jobscript.sh is just a template, and the braces within slurm-jobscript.sh
```
#!/bin/bash
# properties = {properties}
{exec_job}
```
get replaced at the time of job submission.

So even though you don't see 'params' there now, 'params' may be present when a job is actually submitted.

Do the rules being submitted contain 'params'?
Do they refer to 'params' without defining them?

**Comment by lczech** [comment]
Yes, the particular rule that caused the error contains `params`, and works well in a non-slurm setup (when run locally). All params that are used are defined in that rule.

For now, I have "solved" this by editing the `slurm_utils.py` function `format_wildcards` to contain the following:

    if "params" in job_properties:
        job._format_params = Wildcards(fromdict=job_properties['params'])
    else:
        job._format_params = Wildcards()
    if "wildcards" in job_properties:
        job._format_wildcards = Wildcards(fromdict=job_properties['wildcards'])
    else:
        job._format_wildcards = Wildcards()
    if not hasattr(job, 'rule'):
        job.rule = Wildcards()

All three attributes that I check here were causing errors in some rules, and so I added dummies for all of them. Seems to work, but not sure if this is a reasonable solution.

**Comment by rkarnik-kymera** [comment]
Running into this as well. Workaround from @lczech works. It is interesting that this error is only triggered if one of the rules has a param section.

**Comment by percyfal** [comment]
Hi, sorry for the late response; there is a pull request to address this issue: https://github.com/Snakemake-Profiles/slurm/pull/50. {properties} should be populated by snakemake when it creates the job script (https://github.com/snakemake/snakemake/blob/master/snakemake/jobs.py#L863) so all keys should be present; however if there is a TypeError params is removed (https://github.com/snakemake/snakemake/blob/master/snakemake/jobs.py#L881). That being said, I don't know all the inner workings of snakemake. I gather you observe this behaviour both for params and wildcards?
