### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by chrarnold** [Snakemake-Profiles/slurm#52]
Hi, I am a very experienced Snakemake user. I used the traditional --cluster-config so far, and I am trying to see the added value of profile. However, I am having some difficulties with setting it up as well as some fundamental questions, maybe you can help:

1. I want to call sbatch with the --parsable option, but I am not sure where to put that. Could you guide me?
2. In the config.yaml, I can only put cluster-related options, correct? If I, for example, want to use singularity per default when invoking a cluster job, can I also put the various singularity-related options in there? What about --verbose or other flags, how to properly put that into the config?
3. Usually, we specify the location of the output and error files for each workflow in the config.yaml, as the folder is different for each workflow. Is there a way to put this in a generic fashion into the cluster template, like $PROJECTS_FOLDER so that it always works? If so, where and how do I specify the projects folder that is recognized in the config.yaml from the profile folder?

I might have more questions, thanks!

One tip: You may want to put the answer in one of the Issues here how this generally work to the front page. To be honest, it is currently quite cryptic and hard to understand how to use the profiles practically and how to set it up properly.

**Comment by percyfal** [comment]
Hi,

I think my main motivation to switch to profiles at the time was that jobs that timed out would not be automatically resubmitted - I still think that is the case? I also use the cluster configuration together with the profile to configure rules (e.g. constraints), despite the fact that cluster configuration officially deprecated (https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-deprecated). To address your questions:

1. you could put this in the cookiecutter configuration sbatch_defaults, but that would mess with the way jobids are identified by the submit script (https://github.com/Snakemake-Profiles/slurm/blob/a57fad66dd1065c7b479250f098e3fc859473279/%7B%7Bcookiecutter.profile_name%7D%7D/slurm_utils.py#L135; and yes the -P option could be used here, come to think of it). Could you provide an example of what it is you want to do?

2. well, only the options that currently are listed (local-cores etc), but that could obviously be amended. Regarding --verbose and other options, are you referring to snakemake options?

3. you could either set it via sbatch_options (e.g.  --output=logs/slurm-%.err) or similarly in cluster config (see e.g. https://github.com/Snakemake-Profiles/slurm/pull/43)

Feel free to ask more questions! To reduce/remove dependency on cluster-config, the profile should probably be amended with functionality similar to that in https://github.com/Snakemake-Profiles/lsf. And yes, there should be more examples in the README, I agree. I finally got around to moving the tests to github actions, so adding tests/functionality similar to the lsf profile should be easier now. Now I just have to find the time to do it!

**Comment by proteins247** [comment]
Re. 1, I have this question too. How does one specify sbatch options with no parameter value? --parsable is an example of such an option; others include --no-requeue, --exclusive. The way `slurm_utils.submit_job` appears to parse arguments is to assume a --key=val structure, which seems to preclude no-parameter arguments?

```
def submit_job(jobscript, **sbatch_options):
    """Submit jobscript and return jobid."""
    optsbatch_options = [f"--{k}={v}" for k, v in sbatch_options.items()]
```

**Comment by percyfal** [comment]
Hi,

I have made a massive refactoring of the tests in particular (#58), but @chrarnold I have also added some examples to the documentation (see https://github.com/percyfal/slurm/tree/update-tests) and @proteins247 it should now be possible to specify sbatch options with no parameters. Note that the job submission now always adds the --parsable flag as the output is used internally in the submission script. Please see if these changes address you issues. Feedback is welcome!

Cheers,

Per

**Comment by percyfal** [comment]
Closing this issue, feel free to reopen if need be.
