### ISSUE TITLE
why mixed python/python3

### ISSUE THREAD

**Issue by kkmann** [Snakemake-Profiles/slurm#60]
Hi,

I just ran into an issue because the slurm-submit.py template uses #!/usr/bin/env python instead of #!/usr/bin/env python3

https://github.com/Snakemake-Profiles/slurm/blob/a4abc2123e7c7b66f346e8d34601632700ac11a2/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-submit.py#L1

is there a special reason for this?

**Comment by percyfal** [comment]
Hi,

I was recently alerted to this issue and it should be solved in the PR that I just merged. It was just a type on my side.

Cheers,

Per
