### ISSUE TITLE
Reduce dependence upon cookiecutter

### ISSUE THREAD

**Issue by frankier** [Snakemake-Profiles/slurm#63]
I have been using this code as part of https://github.com/frankier/singslurm2/ -- which allows Snakemake within a Singularity container to run SLURM commands on the host. One problem that because I don't want to introduce a dependency upon cookiecutter, I have to use awk to get rid of the templating commands. See: https://github.com/frankier/singslurm2/blob/main/setup.sh . Clearly this approach is a bit fragile.

I was wondering whether all the templated configuration variables could be moved to a file `config.py` and imported from the various scripts? This would help other people who want to configure things programmatically without using cookiecutter. This would also help with linters, since that file could be ignored, and everything else would just be normal Python code. Does it sound okay? Shall I put together a PR?

**Comment by percyfal** [comment]
Hi @frankier,

moving the templated configuration to a separate file is definitely an option. I presume you have in mind something similar to [CookieCutter.py](https://github.com/Snakemake-Profiles/lsf/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/CookieCutter.py)? Would that feature solve the dependency issue that you mention?
