### ISSUE TITLE
Remove dependency on pandas

### ISSUE THREAD

**Issue by frankier** [Snakemake-Profiles/slurm#64]
Pandas is not a dependency of Snakemake. As such it would be nice to not add it an an extra dependency here.

**Comment by percyfal** [comment]
For now, I moved the pandas import to a function that is used in the advanced argument conversion which I guess you're not making use of, right? I agree this dependency should eventually be removed entirely and replaced by simpler functionality as all it does is store the cluster configuration in a table.
