### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType' when claiming nodes=1 with walltime

### ISSUE THREAD

**Issue by zihhuafang** [Snakemake-Profiles/slurm#68]
Hi @percyfal,

I am using this slurm profile on my HPC. My Snakemake version is 5.32.0.

When specifying `nodes=1` in the resources of the rules together with `walltime`, eg:
```
rule fastp_qc:
    input:
        R1 = FASTQDIR + "/{sample}_R1.fastq.gz",
        R2 = FASTQDIR + "/{sample}_R2.fastq.gz"
    output:
        R1_qc = "qc/{sample}_R1.fastq.gz",
        R2_qc = "qc/{sample}_R2.fastq.gz",
        JSON = "qc/{sample}_fastp.json"
    conda:
        "../envs/short_read_mapping.yml"
    params:
        qualified_quality_phred = 15,
        unqualified_percent_limit = 40,
        nova_seq = "-g"
    threads: 10
    resources:
         nodes= 1,
         walltime= "12:00:00"
    shell:
        """
        fastp --thread {threads} -i {input.R1} -o {output.R1_qc} -I {input.R2} -O {output.R2_qc} \
                -j {output.JSON} -q {params.qualified_quality_phred} \
                -u {params.unqualified_percent_limit} \
                {params.nova_seq} >/dev/null
        """
```

I got the following error message for submitting jobs:

```
Traceback (most recent call last):
  File "/mnt/vol008/bio-informatik/fangz/test/test/slurm-submit.py", line 51, in                                                                              <module>
    sbatch_options = slurm_utils.advanced_argument_conversion(sbatch_options)
  File "/mnt/vol008/bio-informatik/fangz/test/test/slurm_utils.py", line 219, in                                                                              advanced_argument_conversion
    time_limit = max(config["TIMELIMIT_MINUTES"])
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

When I changed to `nodes=2`, the error goes away.
The same is true when specifying nodes:1 in `cluster_config.yaml`.

By removing `walltime`, specifying `nodes=1` does not give error. 
I am wondering if it is necessary to always submit jobs to at least two nodes if I want to specify `walltime`.
This does not seem to be necessary to me.  
Is there any way to change this behavior?

Would appreciate your input!
Thanks in advance.
Best wishes,
Zih-Hua

**Comment by percyfal** [comment]
Hi, it seems you are using advanced argument conversion? Keep in mind that this functionality is experimental and may not always work out of the box. It looks like the cluster configuration is missing. Are you submitting to your default cluster or do you have to specify the cluster name? I recently discovered that the `sinfo` calls in `slurm_utils.py` didn't properly take into account cases where jobs are submitted to alternative clusters. This should be fixed in a recent (unmerged) PR.

Note that `walltime` must be an integer representing minutes. Start by modifying this value and see what happens.

**Comment by percyfal** [comment]
@zihhuafang did you solve the issue? Closing now, but feel free to reopen if not.
