### ISSUE TITLE
Getting "/bin/sh: slurm-status.py: command not found" error

### ISSUE THREAD

**Issue by anilthanki** [Snakemake-Profiles/slurm#76]
Hi 

I followed the steps mentioned here and created profile. but I am getting "/bin/sh: slurm-status.py: command not found" error.

I am using Snakemake-6.8.0

Thanks

Anil

**Comment by percyfal** [comment]
@anilthanki did the suggested solution work out for you?

**Comment by anilthanki** [comment]
Hi..

Sorry I have started using simple slurm from @jdblischak https://github.com/jdblischak/smk-simple-slurm 

And its been working well I guess.

Thanks

Anil
