### ISSUE TITLE
Why the resources are not taken from the slurm configuration?

### ISSUE THREAD

**Issue by ekushele** [Snakemake-Profiles/slurm#77]
My rules gets default resources, other then what I gave in slurm profile.
Why?

My slurm profile 
```
{
    "SBATCH_DEFAULTS": "",
    "CLUSTER_NAME": "",
    "CLUSTER_CONFIG": "/path/configs/cluster_config.yml",
    "ADVANCED_ARGUMENT_CONVERSION": "no"
}
```

My "/path/configs/cluster_config.yml":
```
__default__:
  time : 10
  output : "logs/{rule}.{wildcards}.log"
  mem : 4G
  cpus-per-task : 1
```

And the resources for a random rule is:
    `resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp`

Why the resources are not taken from the slurm configuration?

**Comment by percyfal** [comment]
Hi @ekushele, I take it you have solved your issues thanks to the detailed answers above (thanks @jdblischak!)?
