### ISSUE TITLE
add more option on config.yaml

### ISSUE THREAD

**Issue by sravel** [Snakemake-Profiles/slurm#80]
Hello, 
Is it possible to add all snakemake option on config.yaml file like the profile lsl?
https://github.com/Snakemake-Profiles/lsf/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/config.yaml

Thanks

**Comment by percyfal** [comment]
Hi @sravel , are you wondering whether it is possible to add options or whether more options should be listed in the template? If the latter (which I'm assuming), are there any particular options that you feel are missing? I would personally try to keep the list of included options at a minimum though, but I could certainly see including the subset that is used in the lsf profile.

**Comment by sravel** [comment]
Hi,
More options in the config.yaml profile file could be cool. At the moment I add manually `jobs`,  `use-conda` and `use-singularity` slurm options which are really needed. 

Here slurm config.yaml
```
restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
```
and here from lst 
```
latency-wait: "{{cookiecutter.latency_wait}}"
jobscript: "lsf_jobscript.sh"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
restart-times: "{{cookiecutter.restart_times}}"
jobs: "{{cookiecutter.jobs}}"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "{{cookiecutter.max_jobs_per_second}}"
max-status-checks-per-second: "{{cookiecutter.max_status_checks_per_second}}"
```
