### ISSUE TITLE
Specifying GRES (gpu, local storage) and constraints

### ISSUE THREAD

**Issue by holtgrewe** [Snakemake-Profiles/slurm#86]
I have the requirement of specifying

- constraints (e.g., `sbatch -C haswell|broadwell`)
- GPUs (e.g., `--gres=gpu:tesla:1`)
- other GRES types (e.g., `--gres=localtmp:1024` for 1GB of local temporary storage)

I propose that this could be defined as

```
rule myrule:
  # ...
  resources:
    # ...
    gres=[{"type": "gpu", "count": 1}, {"type": "localtmp", "count": 1024}],
    constraint="haswell|broadwell",
```

I have seen some doubts regarding this in other issues. I believe that these are common requirements that Slurm users will have.

What do you think?

**Comment by percyfal** [comment]
Yes, there should definitely be support for this. Adding support for constraint is trivial. Couldn't the gres resources be as simple as 
```
gres=["gpu:tesla:1", "localtmp:1024"]
```
or are there other peculiarities you wish to address?
